### ISSUE TITLE
Sytuacja po stronie ukraińskiej

### ISSUE THREAD

**Issue by sypianski** [bekonowicz/granica-monit#2]
- [ ] Dodać cztery nowe kolumny w tabeli:
    1. samochody (typ: liczba)
    2. czas samochodów: (typ: liczba, skala 1-3)
    3. piesi (typ: liczba)
    4. czas pieszych (typ: liczba, skala 1-3)
- [ ] Zobrazowanie powyższych kolumn jako ikon na mapie:
    - [ ]  kolumny 2 i 4 jako kolorki, pewnie w tej samej tonacji jak niezrobiona jeszcz stara kolumna

**Comment by jarekkopec** [comment]
W uproszczonej wersji (po ustaleniach) zostało zrobione, jest na main.
